### ISSUE TITLE
Feature request: adding an access key for the search box

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#27]
Hi,

it would be nice, for keyboard-centric people like me :-), to add an `accesskey` attribute for the DocsForge search box. I'd suggest "s", as it is the initial of "search" and also what Doxygen uses in its generated HTML pages. What do you think?

**Comment by erez-o** [comment]
Sure,

I personally never use it, but implementation seems pretty straightforward. 

I'll go with your suggestion "s", and if other users want to change it in the future, it's also simple to make it customizable.

Thanks :)

**Comment by erez-o** [comment]
Reopening issue.

Did some investigating, and seems it's not advised:

Quoting from https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/accesskey

> In addition to poor browser support, there are numerous concerns with the accesskey attribute:
An accesskey value can conflict with a system or browser keyboard shortcut, or assistive technology functionality. 
What may work for one combination of operating system, assistive technology, and browser may not work with other combinations.
Certain accesskey values may not be present on certain keyboards, especially when internationalization is a concern. So adapting to specific languages could cause further problems.
accesskey values that rely on numbers may be confusing to individuals experiencing cognitive concerns, where the number doesn't have a logical association with the functionality it triggers. 
Informing the user that accesskeys are present, so that they are aware of the functionality. If the system lacks a method of notifying the user about this feature, the user might accidentally activate accesskeys.
**Because of these issues, it is generally advised not to use accesskeys for most general-purpose websites and web apps.**

However, in the next update, maintainers will be able to add custom javascript snippets to their project docs, and without testing it, it's supposed to be a 1 line code:

```js
$("#search-in-project").attr("accesskey", "s");
```

Leavnig issue open for now.

**Comment by gennaroprota** [comment]
Thanks for researching the issue. The [current Wikipedia entry](https://en.wikipedia.org/w/index.php?title=Access_key&oldid=964877178) also hints at possible problems (but Wikipedia itself uses an access key for its search box). It's not a big deal, either way.

**Comment by erez-o** [comment]
Closing. Since version 3.4.16 custom javascript can be added to any project.

Added a `accesskey` example snippet to the [documentation](https://help.docsforge.com/master/themes-css-javascript/#accesskey), I checked that it indeed works, so if it helps you go right ahead.

Since it's not recommended by both Mozilla and Wikipedia, I don't currently intend on adding it across site.
