### ISSUE TITLE
Use of the term "latest", in lieu of "main", "primary" or "principal"

### ISSUE THREAD

**Issue by gennaroprota** [erez-o/docsforge#28]
Hi,

in several places, the DocsForge user interface uses the term "latest" to refer to what is AFAIU the "main" documentation set. This is IMHO misleading because e.g. the documentation for the master branch (marked as "latest" by default) may, in fact, be older than that of a given branch (not only because e.g. the branch docs were generated later on DocsForge, but also because the branch can really be ahead of master by some commits). So, I'd suggest using one of the terms "main", "primary" or "principal", in this case (I'm not able to pick up what the best one is, because I'm not a native speaker and I might actually miss the exact concept you had in mind).

**Comment by erez-o** [comment]
Thanks, 

I too faced the same issue, and I chose `latest` only because it's the common term used in other documentation framework I've seen. Internally I actually save this db field as `primary` because `latest` doesn't feel right, but maybe it's because both of us are not native speakers.

I'll leave this issue open for now.

Starting from the next release, using javascript, any maintainer can change this term on their project, I'll add a relevant code snippet to the docs.

**Comment by gennaroprota** [comment]
Thanks!
